on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Deploy

jobs:
  deploy:
    name: deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - uses: actions-hub/kubectl@master
        with:
          args: apply -f manifest.yml
