on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Deploy

jobs:
  deploy:
    name: deploy 
    runs-on: ubuntu-latest
    steps:
      - name: Update deployment
        uses: ianbelcher/eks-kubectl-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: "latest"
          NAMESPACE: "prod"
        with:
          aws_access_key_id: ${{ secrets.AWS_PRIMARY_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_PRIMARY_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_PRIMARY_REGION }}
          cluster_name: cluster-eks
          args: set image --namespace $NAMESPACE --record deployment/DEPLOYMENT_NAME DEPLOYMENT_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
loy:
    name: deploy 
    runs-on: ubuntu-latest
    steps:
      - name: Update deployment
        uses: ianbelcher/eks-kubectl-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: "latest"
          NAMESPACE: "prod"
        with:
          aws_access_key_id: ${{ secrets.AWS_PRIMARY_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_PRIMARY_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_PRIMARY_REGION }}
          cluster_name: cluster-eks
          args: set image --namespace $NAMESPACE --record deployment/DEPLOYMENT_NAME DEPLOYMENT_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
